Fixed verify in unit tests
alejo740/GithubSubscribers pull request #13
Opened 2016-09-15 18:57 UTC by alejo740

- Added verify method to view mock object
- Removed unused constant in constants class

2016-09-15 19:02 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
>          OnFinishedListenerCallBack.getValue().onFinishedUser(user);
Use camelCase to rename `OnFinishedListenerCallBack`.

2016-09-15 19:02 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> +        verify(view).showSubscriberDetails(user);
You should verify that the progress indicator is shown.

2016-09-15 19:02 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> -        view.showUserError(messageId);
You should verify that the progress indicator is shown.

2016-09-15 19:02 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> -        view.showUserError(messageId);
You should verify that the progress indicator is shown.

2016-09-15 19:02 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> -        view.showSubscriberUserRepositories(repoList);
You should verify that the progress indicator is shown.

2016-09-15 19:03 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> -        view.showUserError(messageId);
You should verify that the progress indicator is shown.

2016-09-15 19:03 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> -        view.showUserError(messageId);
You should verify that the progress indicator is shown.

2016-09-15 19:03 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscriberslist/SubscribersListInteractorTest.java
>          OnFinishedListenerCallBack.getValue().onResponse(subscriberList);
Remane it using camelCase.

2016-09-15 19:03 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscriberslist/SubscribersListInteractorTest.java
> -        view.showSubscribersList(subscriberList);
You should verify that the progress indicator is shown.

2016-09-15 19:03 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscriberslist/SubscribersListInteractorTest.java
> -        view.showSubscribersError(messageId);
You should verify that the progress indicator is shown.

2016-09-15 19:03 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscriberslist/SubscribersListInteractorTest.java
> -        view.showSubscribersError(messageId);
You should verify that the progress indicator is shown.

2016-09-15 19:04 UTC, lucaslabs requested changes

2016-09-15 19:04 UTC, lucaslabs approved these changes

2016-09-16 13:30 UTC, lucaslabs commented on app/src/main/java/com/github/globant/githubsubscribers/subscribersdetail/presenter/SubscriberDetailPresenterImpl.java
> +            view.toggleProgressIndicator(false);
The natural order of the experience is: hide the loading then show the data, so, put `view.toggleProgressIndicator(false);` first then show the data.

2016-09-16 13:30 UTC, lucaslabs commented on app/src/main/java/com/github/globant/githubsubscribers/subscribersdetail/presenter/SubscriberDetailPresenterImpl.java
> +            view.toggleProgressIndicator(false);
Same here.

2016-09-16 13:30 UTC, lucaslabs commented on app/src/main/java/com/github/globant/githubsubscribers/subscribersdetail/presenter/SubscriberDetailPresenterImpl.java
> +            view.toggleProgressIndicator(false);
Same.

2016-09-16 13:30 UTC, lucaslabs commented on app/src/main/java/com/github/globant/githubsubscribers/subscribersdetail/presenter/SubscriberDetailPresenterImpl.java
> +            view.toggleProgressIndicator(false);
Same.

2016-09-16 13:31 UTC, lucaslabs commented on app/src/main/java/com/github/globant/githubsubscribers/subscribersdetail/view/SubscriberDetailFragment.java
> +        progressBar = new ProgressDialog(view.getContext());
Why not declaring the Progress indicator in XML?

2016-09-16 13:32 UTC, lucaslabs commented on app/src/main/java/com/github/globant/githubsubscribers/subscriberslist/presenter/SubscribersListPresenterImpl.java
> +            view.toggleProgress(false);
Hide the progress firts then show the error message.

2016-09-16 13:35 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> +        OnFinishedListenerCallback.getValue().onFailureUser(errorMessage, typeError);
Remane the variable using camelCase to `onFinishedListenerCallback`.

2016-09-16 13:35 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> +        OnFinishedListenerCallback.getValue().onFailureUser(errorMessage, typeError);
Remane the variable using camelCase to `onFinishedListenerCallback`.

2016-09-16 13:35 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> +        OnFinishedListenerCallback.getValue().onFinishedRepository(repoList);
Remane the variable using camelCase to `onFinishedListenerCallback`.

2016-09-16 13:35 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> +        OnFinishedListenerCallback.getValue().onFailureRepository(errorMessage, typeError);
Remane the variable using camelCase to `onFinishedListenerCallback`.

2016-09-16 13:35 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscribersdetail/SubscriberDetailPresenterTest.java
> +        OnFinishedListenerCallback.getValue().onFailureRepository(errorMessage, typeError);
Remane the variable using camelCase to `onFinishedListenerCallback`.

2016-09-16 13:36 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscriberslist/SubscribersListInteractorTest.java
> +        OnFinishedListenerCallback.getValue().onResponse(subscriberList);
Remane the variable using camelCase to `onFinishedListenerCallback`.

2016-09-16 13:36 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscriberslist/SubscribersListInteractorTest.java
> +        OnFinishedListenerCallback.getValue().onFailure(errorMessage, typeError);
Remane the variable using camelCase to `onFinishedListenerCallback`.

2016-09-16 13:36 UTC, lucaslabs commented on app/src/test/java/com/github/globant/githubsubscribers/subscriberslist/SubscribersListInteractorTest.java
> +        OnFinishedListenerCallback.getValue().onFailure(errorMessage, typeError);
Remane the variable using camelCase to `onFinishedListenerCallback`.

2016-09-16 13:36 UTC, lucaslabs requested changes

2016-09-16 14:26 UTC, juliocatano commented on app/src/main/java/com/github/globant/githubsubscribers/subscribersdetail/view/SubscriberDetailFragment.java
> +        progressBar = new ProgressDialog(view.getContext());
+1

2016-09-16 18:21 UTC, lucaslabs commented on app/build.gradle
> +    compile "com.github.d-max:spots-dialog:$rootProject.ext.spotsDialogVersion"
Please keep it simple and use the progress dialog.

2016-09-16 18:21 UTC, lucaslabs requested changes

2016-09-16 18:45 UTC, lucaslabs commented
LG

2016-09-16 19:31 UTC, lucaslabs approved these changes

2016-09-16 19:31 UTC, merged